### ISSUE TITLE
app crash when media playing

### ISSUE THREAD

**Issue by wizard-gg** [zzeneg/qmk-hid-host#3]
Hi
any time I play any music with Media Player in windows application crash with this log:

I'm using windows 11
```
thread '<unnamed>' panicked at src\providers\media\windows.rs:45:84:
called `Result::unwrap()` on an `Err` value: Error { code: HRESULT(0x80070015), message: "The device is not ready." }
fatal runtime error: Rust panics must be rethrown
```

**Comment by zzeneg** [comment]
Thanks for the report, I can reproduce it as well. I'll fix it soon.

**Comment by zzeneg** [comment]
Should work now.

**Comment by wizard-gg** [comment]
Thanks for update but I got new error:

I find out something, if I open app when music is playing its works fine but while app is open if I try to play music app will give me this error.

`2024-04-28T14:20:48.801426Z ERROR qmk_hid_host::providers::media::windows: Can not get media properties: The device is not ready. (0x80070015)`

**Comment by zzeneg** [comment]
It's the same error - I fixed only the crash caused by it. I believe the error is caused by the Media Player itself, it does not even work with native Windows widget for me, no info there:
![image](https://github.com/zzeneg/qmk-hid-host/assets/910255/f841e09d-f6db-48e6-928d-07831926bc2e)
I tried different ways to get media info from Media Player with no luck - while Spotify or YouTube work without issues.
